TEXTS = {
    "English": {
        "title": "Complaints Management System",
        "admin_login": "Admin Login",
        "username": "Username",
        "password": "Password",
        "login_button": "Login",
        "login_success": "Login successful.",
        "login_error": "Incorrect username or password.",
        "select_section": "Choose a section",
        "file_complaint": "File a new complaint",
        "manage_complaints": "Manage Complaints",
        "analytics": "Analytics",
        "export_data": "Export Data",
        "logout": "Log out",
        "new_complaint": "File a New Complaint",
        "name": "Name",
        "email": "Email",
        "complaint_type": "Complaint Type",
        "complaint_types": ["Complaint", "Inquiry", "Suggestion"],
        "complaint_content": "Complaint Content",
        "priority": "Complaint Priority",
        "priorities": ["High", "Medium", "Low"],
        "submit": "Submit",
        "complaint_success": "Complaint submitted successfully.",
        "fill_fields": "Please fill in all fields.",
        "invalid_email": "Please enter a valid email address.",
        "manage_complaints_title": "View and Manage Complaints",
        "filter_complaints": "Filter Complaints",
        "status": "Status",
        "type": "Type",
        "priority_label": "Priority",
        "update_status": "Update Complaint Status",
        "complaint_id": "Complaint ID",
        "new_status": "Select New Status",
        "statuses": ["In Progress", "Resolved", "Rejected"],
        "update_button": "Update Status",
        "status_updated": "Complaint status updated.",
        "satisfaction": "Customer Satisfaction Rating (Optional)",
        "rating": "Service Rating (1 to 5)",
        "feedback": "Additional Comments",
        "submit_rating": "Submit Rating",
        "rating_success": "Rating submitted. Thank you!",
        "search_complaint": "Search for Complaint by ID",
        "search_id": "Enter Complaint ID",
        "search_button": "Search",
        "complaint_details": "Complaint Details:",
        "no_complaint": "No complaint found with this ID.",
        "no_complaints": "No complaints registered.",
        "analytics_title": "Complaint Analytics",
        "by_category": "Complaints by Category",
        "by_status": "Complaints by Status",
        "status_distribution": "Status Distribution",
        "by_priority": "Complaints by Priority",
        "no_data": "No data available for analysis.",
        "export_title": "Export Data",
        "download_csv": "Download CSV",
        "no_data_export": "No data to export.",
        "notifications": "Notifications",
        "email_error": "Error while sending email: {e}",
        "email_subject_new": "New Complaint",
        "email_body_new": "New complaint received from {name}.\nEmail: {email}\nType: {category}\nPriority: {priority}\n\nContent:\n{content}",
        "email_subject_update": "Complaint Status Update",
        "email_body_update": "Complaint ID {id} status changed to: {status}.",
        "notification_status": "Complaint ID {id} status updated to {status}.",
        "admin_expander": "Are you an admin? Click here to log in",
        "total_complaints": "Total Complaints",
        "resolved_complaints": "Resolved Complaints",
        "resolution_rate": "Resolution Rate",
        "monthly_trend": "Monthly Complaint Trend",
        "month": "Month",
        "number_of_complaints": "Number of Complaints",
    },
    "Arabic": {
        "title": "نظام إدارة الشكاوى",
        "admin_login": "تسجيل دخول الأدمن",
        "username": "اسم المستخدم",
        "password": "كلمة المرور",
        "login_button": "تسجيل الدخول",
        "login_success": "تم تسجيل الدخول بنجاح.",
        "login_error": "اسم المستخدم أو كلمة المرور غير صحيحة.",
        "select_section": "اختر القسم",
        "file_complaint": "تقديم شكوى جديدة",
        "manage_complaints": "إدارة الشكاوى",
        "analytics": "التحليلات",
        "export_data": "تصدير البيانات",
        "logout": "تسجيل الخروج",
        "new_complaint": "تقديم شكوى جديدة",
        "name": "الاسم",
        "email": "البريد الإلكتروني",
        "complaint_type": "نوع الشكوى",
        "complaint_types": ["شكوى", "استفسار", "اقتراح"],
        "complaint_content": "محتوى الشكوى",
        "priority": "أولوية الشكوى",
        "priorities": ["عالية", "متوسطة", "منخفضة"],
        "submit": "إرسال",
        "complaint_success": "تم تقديم الشكوى بنجاح.",
        "fill_fields": "من فضلك، املأ جميع الحقول.",
        "invalid_email": "من فضلك، أدخل بريدًا إلكترونيًا صالحًا.",
        "manage_complaints_title": "عرض وإدارة الشكاوى",
        "filter_complaints": "تصفية الشكاوى",
        "status": "الحالة",
        "type": "النوع",
        "priority_label": "الأولوية",
        "update_status": "تحديث حالة الشكوى",
        "complaint_id": "رقم الشكوى",
        "new_status": "اختر الحالة الجديدة",
        "statuses": ["قيد المعالجة", "تم الحل", "مرفوضة"],
        "update_button": "تحديث الحالة",
        "status_updated": "تم تحديث حالة الشكوى.",
        "satisfaction": "تقييم رضا العملاء (اختياري)",
        "rating": "تقييم الخدمة (من 1 إلى 5)",
        "feedback": "تعليقات إضافية",
        "submit_rating": "إرسال التقييم",
        "rating_success": "تم إرسال التقييم. شكراً لك!",
        "search_complaint": "البحث عن شكوى برقم",
        "search_id": "أدخل رقم الشكوى",
        "search_button": "بحث",
        "complaint_details": "تفاصيل الشكوى:",
        "no_complaint": "لا توجد شكوى بهذا الرقم.",
        "no_complaints": "لا توجد شكاوى مسجلة.",
        "analytics_title": "تحليلات الشكاوى",
        "by_category": "الشكاوى حسب النوع",
        "by_status": "الشكاوى حسب الحالة",
        "status_distribution": "توزيع الحالات",
        "by_priority": "الشكاوى حسب الأولوية",
        "no_data": "لا توجد بيانات متاحة للتحليل.",
        "export_title": "تصدير البيانات",
        "download_csv": "تنزيل CSV",
        "no_data_export": "لا توجد بيانات للتصدير.",
        "notifications": "الإشعارات",
        "email_error": "خطأ أثناء إرسال البريد الإلكتروني: {e}",
        "email_subject_new": "شكوى جديدة",
        "email_body_new": "تم استلام شكوى جديدة من {name}.\nالبريد: {email}\nالنوع: {category}\nالأولوية: {priority}\n\nالمحتوى:\n{content}",
        "email_subject_update": "تحديث حالة الشكوى",
        "email_body_update": "تم تغيير حالة الشكوى رقم {id} إلى: {status}.",
        "notification_status": "تم تحديث حالة الشكوى رقم {id} إلى {status}.",
        "admin_expander": "هل أنت أدمن؟ اضغط هنا لتسجيل الدخول",
        "total_complaints": "إجمالي الشكاوى",
        "resolved_complaints": "الشكاوى المحلولة",
        "resolution_rate": "نسبة الحل",
        "monthly_trend": "الاتجاه الشهري للشكاوى",
        "month": "الشهر",
        "number_of_complaints": "عدد الشكاوى",
        "your_email": "بريدك الإلكتروني",
    }
}
